#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-wasm-build:
    name: Build extension binaries for duckdb-wasm (experimental)
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      extension_name: iceberg
      duckdb_version: v1.4.1
      ci_tools_version: v1.4.1
      exclude_archs: 'linux_amd64;linux_arm64;linux_amd64_musl;osx_amd64;osx_arm64;windows_amd64;windows_amd64_mingw'
      extra_toolchains: 'python3'

  duckdb-wasm-deploy:
    name: Deploy extension binaries for duckdb-wasm (experimental)
    needs: duckdb-wasm-build
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_deploy.yml@main
    secrets: inherit
    with:
      extension_name: iceberg
      duckdb_version: v1.4.1
      ci_tools_version: v1.4.1
      exclude_archs: 'linux_amd64;linux_arm64;linux_amd64_musl;osx_amd64;osx_arm64;windows_amd64;windows_amd64_mingw'
      deploy_latest: ${{ github.ref == 'refs/heads/wasm' }}
      deploy_versioned: ${{ github.ref == 'refs/heads/wasm' }}
